Add Azure MySQL
charles-001/dolphie pull request #56
Opened 2024-03-19 00:36 UTC by spacentropy

Hello! Thanks for the awesome tool.
Here's the Azure MySQL compatibility.

2024-03-19 04:56 UTC, charles-001 commented
Hi @spacentropy - thank you for your contribution! I just have 1 comment about it :)

2024-03-28 03:44 UTC, charles-001 commented
@spacentropy Following up on this - did you see my previous comment?

2024-03-28 04:51 UTC, spacentropy commented
@charles-001 sorry I don't see any comments. Maybe you've left a comment but did not finish the review?

2024-03-28 06:13 UTC, charles-001 requested changes

2024-03-28 06:14 UTC, charles-001 commented
> @charles-001 sorry I don't see any comments. Maybe you've left a comment but did not finish the review?

Ah... I left a comment, but it seems I needed to request a change. Sorry about that!

2024-03-28 06:16 UTC, spacentropy commented on dolphie/__init__.py
> +        if self.azure:
Right, fixed

2024-03-28 19:49 UTC, merged